org: tmdgenaistudents06
app: my-service06
service: my-service06

custom:
  stage: ${sls:stage}                         # dev 등
  usersTableName: ${self:service}-${self:custom.stage}-users

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2

  deploymentBucket:
    name: tmd-genai1-students06
    blockPublicAccess: true
    serverSideEncryption: AES256

  environment:
    USERS_TABLE: ${self:custom.usersTableName}

  # v4 권장 문법
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.usersTableName}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}     # ✅ 환경변수와 동일하게 통일
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  getUser:
    handler: handler.getUser
    events:
      - http:
          path: users/{id}
          method: get
          cors: true

  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users/{id}
          method: put
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
